[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mergenthaler"
dynamic = ["version"]
description = "A blogging platform and markup language."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Jack Huey", email = "jhhuey@icloud.com" }
]
dependencies = [
    "colour>=0.1.5",
    "Flask>=3.1.3",
    "Jinja2>=3.1.6",
    "packaging>=26.3",
    "Requests>=2.34.2",
    "waitress>=3.0.2",
]

[tool.setuptools]
packages.find = { where = ["src"] }

[project.scripts]
mg = "mergenthaler.__main__:main"

[tool.setuptools.package-data]
mergenthaler = ["src/defaultSite/*.html"]

[tool.setuptools_scm]